### ISSUE TITLE
`time.thread_time` is not available on some OS X builds

### ISSUE THREAD

**Issue by ghost** [belm0/perf-timer#3]
It appears `time.thread_time` is not available on mac os (https://bugs.python.org/issue32093) and thus trying to use this package will raise `ImportError` 😢  
```python-traceback
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-277-0f19c673cd74> in <module>
----> 1 from perf_timer import PerfTimer, HistogramObserver

~/opt/anaconda3/envs/py37/lib/python3.7/site-packages/perf_timer/__init__.py in <module>
----> 1 from ._impl import (PerfTimer, ThreadPerfTimer, AverageObserver,
      2                     StdDevObserver, HistogramObserver, measure_overhead)
      3 try:
      4     from ._trio import trio_perf_counter, TrioPerfTimer
      5 except ImportError:

~/opt/anaconda3/envs/py37/lib/python3.7/site-packages/perf_timer/_impl.py in <module>
      8 from inspect import iscoroutinefunction
      9 from multiprocessing import Lock
---> 10 from time import perf_counter, thread_time
     11 
     12 from perf_timer._histogram import ApproximateHistogram

ImportError: cannot import name 'thread_time' from 'time' (unknown location)
```

**Comment by belm0** [comment]
That's disappointing.  It sounds like OS X "El Capitan" and earlier will not have `thread_time`.

**Comment by ghost** [comment]
I am on mac os Catalina (10.15) and see this error (Python 3.7.4)

**Comment by pquentin** [comment]
macOS Big Sur (11.2.1) does not have `thread_time` either on Python 3.9.2. This should probably be reported to CPython, as they clearly thought it would work since Python 3.7.

**Comment by belm0** [comment]
> macOS Big Sur (11.2.1) does not have thread_time either on Python 3.9.2

thread_time is there for me on Python 3.7 (OS X High Sierra, 10.13)

This might be an issue that varies with particular Python builds.

```
$ python
Python 3.7.7 (default, Oct  5 2020, 09:18:33)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from time import thread_time
```

**Comment by pquentin** [comment]
Right, the Homebrew builds have `thread_time`, but the Anaconda and python.org builds don't. :/

**Comment by belm0** [comment]
Does the fix in PR #4 look reasonable?

**Comment by ghost** [comment]
Looks entirely reasonable to me :) ...Although that python.org build `!=` homebrew build `!=` anaconda build is a first for me. Where should we report this?

**Comment by belm0** [comment]
This assessment from the cited issue is particularly dubious:

> I'm not sure if it is worthwhile to implement this fairly specialized function for older macOS releases due to the maintenance cost.

... considering that having Python releases not offer the same functions across all major OS's is a huge maintenance cost for everyone to bear.

> Where should we report this?

I don't know, and https://wiki.python.org/moin/WhereDoIReportThis%3F doesn't help.
So I guess start on bpo?

https://bugs.python.org/issue43370
